### ISSUE TITLE
Error: Cannot find module 'safe-buffer'

### ISSUE THREAD

**Issue by dm-grinko** [iamclaytonray/node-blog#2]
Error: Cannot find module 'safe-buffer'
https://monosnap.com/file/Vygu7DQLzr6umUQAr1CZ2hsLvUpKWI

**Comment by iamclaytonray** [comment]
What's your version of Node and your OS?

**Comment by dm-grinko** [comment]
Node 8.2.1
Sierra 10.12.3

**Comment by iamclaytonray** [comment]
Cool. I didn't realize how outdated this repo was. I just updated a whole bunch of stuff (including removing unneeded parts) so you should be all set. If the issue persists, let me know.

**Comment by dm-grinko** [comment]
I have fixed it. I have installed nodejs v6.11.2 LTS
Thank you Clayton for sharing your code.

**Comment by iamclaytonray** [comment]
Hmmm. That's not really a solution. Moving forward, everything I put up on Github will be Dockerized, which will eliminate the "works on my machine" problem. You could probably `npm install` or `yarn add` safe-buffer in Node v8+
